### ISSUE TITLE
Add a json data field that can be used to update any sort of meta data

### ISSUE THREAD

**Issue by maisnamraju** [gobeam/truthy#14]
**Is your feature request related to a problem? Please describe.**
Looking at whats out there now, it will be very useful to have another column that would be a json field where we can store details like user tenancy data or external details that fall outside the context of authentication. 

Example of such a thing was I wanted to some user data that would be available using the `/profile` api like external API keys.

**Comment by gobeam** [comment]
I think right now I will be not implementing this feature since it is currently it is not required in base cms. If you want to feel free to add this I will review it. Thanks.

**Comment by maisnamraju** [comment]
will send you a pr.
