### ISSUE TITLE
Can You please add MySQL ?

### ISSUE THREAD

**Issue by davidtim** [gobeam/truthy#15]
Can you please also add mysql for database option?

**Comment by gobeam** [comment]
Since we are using Typeform and I've not included any raw SQL I think you can easily change its DB driver to MySQL without any issue. You can try and let me know if you face any issues @davidtim .

**Comment by davidtim** [comment]
@gobeam It's working after install mysql driver and I also have to comment out isUnique in Permission table. But now api-docs is not working

**Comment by gobeam** [comment]
@davidtim api-docs only works in the development environment meaning you have to set NODE_ENV=development to access it.

**Comment by davidtim** [comment]
Thank you so much for this project! It's like found a god mine
