### ISSUE TITLE
Ability to assign multiple roles to a user

### ISSUE THREAD

**Issue by xXBlackHawkXx** [gobeam/truthy#16]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to assign multiple roles to a user. 
For example role 1 has x permissions, and role 2 has y permissions.
It would be nice to not have to create a third role with x and y permissions to cover both roles.

**Comment by gobeam** [comment]
I would not describe this as an issue but as a feature request. If you want to add this feature to this API you're more than welcome but for now, I'm closing this issue @xXBlackHawkXx .
