### ISSUE TITLE
env variable not being called in ormconfig.ts

### ISSUE THREAD

**Issue by nksmkj7** [gobeam/truthy#17]
In ormconfig.ts, env variables are returned as undefined. While debugging, I found that ormconfig.ts executes before app.module.ts, hence ormconfig.ts doesn't have an idea about process.env. 

How did I fix it? 
 1. Installed @nestjs/config
 2. In ormconfig.ts,  
 ```js
import { ConfigModule } from '@nestjs/config';
ConfigModule.forRoot();
```

**Comment by gobeam** [comment]
@nksmkj7 this app takes the ENV variable from YML file inside config folder in accordance with NODE_ENV passed. It does not take the environment variables from the .env file. you have to either pass it directly in the NPM command or use YML config files. Let me know if it helps.
