### ISSUE TITLE
Please update documentation

### ISSUE THREAD

**Issue by duylddev** [gobeam/truthy#21]
We want to use Truthy for a simple project (crud), so I clone it to my local machine to test.

After running commands migrate/seed. Go to login screen, login and got `relation user not found` => need to set `synchronize: true`

login => wrong password (might be not Truthy@123 with jwt secret = example@123)
=> Register to manually set admin
=> got `QueryFailedError: null value in column "address" of relation "user" violates not-null constraint`.

I really like this project and want to apply it to my company project but it seems lack of documentation and has some bugs. It's not about login/register bug I've got, it's about I don't feel safe applying Truthy to my company production project

Thanks,

![image](https://user-images.githubusercontent.com/9783862/200374882-6cfe48e2-7bfe-4960-ab6a-966f37d38da9.png)
![image](https://user-images.githubusercontent.com/9783862/200374909-18008410-fd4e-4d3c-b52d-9bd651c4eb1c.png)
![image](https://user-images.githubusercontent.com/9783862/200375001-a9a23551-d62b-4052-adbb-93998c03bb79.png)

**Comment by gobeam** [comment]
@duylddev I think you made some mistake on the configuration, you need to add your database name in the key "database" inside "db" in your config file determined by the NODE_ENV you set like if you pass NODE_ENV as "development" it will give first priority to development.yml and if nothing is found it defaults back to default.yml. Right now I'm caught up with work but I will make sure to add proper documentation when I'm free. Thanks for your valuable suggestion.
