### ISSUE TITLE
Could you please tell me the version of Node.js used in this project and whether it supports using package-lock.json? I cannot run this project now.

### ISSUE THREAD

**Issue by lorsque-sir** [gobeam/truthy#25]
error TS2688: Cannot find type definition file for 'ioredis'.
  The file is in the program because:
    Entry point for implicit type library 'ioredis'
node_modules/@nestjs/typeorm/dist/common/typeorm.decorators.d.ts:2:10 - error TS2305: Module '"typeorm"' has no exported member 'DataSource'.

**Comment by imdocik** [comment]
node:14

**Comment by dvtung1** [comment]
You can use docker to run the service in the container. Everything should be ready to go
